version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  springboot-resful-webservices:
    container_name: springboot-resful-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      mysqldb:
        condition: service_healthy  # Ensures MySQL is ready
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
